version: '3.8'

services:
  db:
    image: postgres:15-alpine # molde estático pré-fabricado. O compose vai baixar a imagem do PostgreSQL 15 com base no Alpine Linux, que é uma distribuição leve e segura.
    container_name: postgres_anotacoes
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: anotacoes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: fastapi_anotacoes
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://admin:adminpassword@db:5432/anotacoes

volumes:
  postgres_data: